#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ToursitAttractions.Droid.Shared.Resource", IsApplication=false)]

namespace ToursitAttractions.Droid.Shared
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public static int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010015
			public static int buttonSize = 2130771989;
			
			// aapt resource value: 0x7f010001
			public static int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f01001a
			public static int circleCrop = 2130771994;
			
			// aapt resource value: 0x7f010016
			public static int colorScheme = 2130771990;
			
			// aapt resource value: 0x7f010019
			public static int imageAspectRatio = 2130771993;
			
			// aapt resource value: 0x7f010018
			public static int imageAspectRatioAdjust = 2130771992;
			
			// aapt resource value: 0x7f010011
			public static int layoutManager = 2130771985;
			
			// aapt resource value: 0x7f010006
			public static int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public static int mapType = 2130771968;
			
			// aapt resource value: 0x7f010013
			public static int reverseLayout = 2130771987;
			
			// aapt resource value: 0x7f010017
			public static int scopeUris = 2130771991;
			
			// aapt resource value: 0x7f010012
			public static int spanCount = 2130771986;
			
			// aapt resource value: 0x7f010014
			public static int stackFromEnd = 2130771988;
			
			// aapt resource value: 0x7f010007
			public static int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public static int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public static int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public static int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public static int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public static int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public static int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public static int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public static int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050019
			public static int colorAccent = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public static int colorFabRipple = 2131034138;
			
			// aapt resource value: 0x7f050017
			public static int colorPrimary = 2131034135;
			
			// aapt resource value: 0x7f050018
			public static int colorPrimaryDark = 2131034136;
			
			// aapt resource value: 0x7f05000e
			public static int common_action_bar_splitter = 2131034126;
			
			// aapt resource value: 0x7f05001b
			public static int common_google_signin_btn_text_dark = 2131034139;
			
			// aapt resource value: 0x7f05000f
			public static int common_google_signin_btn_text_dark_default = 2131034127;
			
			// aapt resource value: 0x7f050011
			public static int common_google_signin_btn_text_dark_disabled = 2131034129;
			
			// aapt resource value: 0x7f050012
			public static int common_google_signin_btn_text_dark_focused = 2131034130;
			
			// aapt resource value: 0x7f050010
			public static int common_google_signin_btn_text_dark_pressed = 2131034128;
			
			// aapt resource value: 0x7f05001c
			public static int common_google_signin_btn_text_light = 2131034140;
			
			// aapt resource value: 0x7f050013
			public static int common_google_signin_btn_text_light_default = 2131034131;
			
			// aapt resource value: 0x7f050015
			public static int common_google_signin_btn_text_light_disabled = 2131034133;
			
			// aapt resource value: 0x7f050016
			public static int common_google_signin_btn_text_light_focused = 2131034134;
			
			// aapt resource value: 0x7f050014
			public static int common_google_signin_btn_text_light_pressed = 2131034132;
			
			// aapt resource value: 0x7f05001d
			public static int common_plus_signin_btn_text_dark = 2131034141;
			
			// aapt resource value: 0x7f050006
			public static int common_plus_signin_btn_text_dark_default = 2131034118;
			
			// aapt resource value: 0x7f050008
			public static int common_plus_signin_btn_text_dark_disabled = 2131034120;
			
			// aapt resource value: 0x7f050009
			public static int common_plus_signin_btn_text_dark_focused = 2131034121;
			
			// aapt resource value: 0x7f050007
			public static int common_plus_signin_btn_text_dark_pressed = 2131034119;
			
			// aapt resource value: 0x7f05001e
			public static int common_plus_signin_btn_text_light = 2131034142;
			
			// aapt resource value: 0x7f05000a
			public static int common_plus_signin_btn_text_light_default = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public static int common_plus_signin_btn_text_light_disabled = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public static int common_plus_signin_btn_text_light_focused = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public static int common_plus_signin_btn_text_light_pressed = 2131034123;
			
			// aapt resource value: 0x7f050002
			public static int place_autocomplete_prediction_primary_text = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int place_autocomplete_prediction_primary_text_highlight = 2131034115;
			
			// aapt resource value: 0x7f050004
			public static int place_autocomplete_prediction_secondary_text = 2131034116;
			
			// aapt resource value: 0x7f050001
			public static int place_autocomplete_search_hint = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int place_autocomplete_search_text = 2131034112;
			
			// aapt resource value: 0x7f050005
			public static int place_autocomplete_separator = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f06000a
			public static int item_touch_helper_max_drag_scroll_per_frame = 2131099658;
			
			// aapt resource value: 0x7f060000
			public static int place_autocomplete_button_padding = 2131099648;
			
			// aapt resource value: 0x7f060008
			public static int place_autocomplete_powered_by_google_height = 2131099656;
			
			// aapt resource value: 0x7f060009
			public static int place_autocomplete_powered_by_google_start = 2131099657;
			
			// aapt resource value: 0x7f060003
			public static int place_autocomplete_prediction_height = 2131099651;
			
			// aapt resource value: 0x7f060004
			public static int place_autocomplete_prediction_horizontal_margin = 2131099652;
			
			// aapt resource value: 0x7f060005
			public static int place_autocomplete_prediction_primary_text = 2131099653;
			
			// aapt resource value: 0x7f060006
			public static int place_autocomplete_prediction_secondary_text = 2131099654;
			
			// aapt resource value: 0x7f060002
			public static int place_autocomplete_progress_horizontal_margin = 2131099650;
			
			// aapt resource value: 0x7f060001
			public static int place_autocomplete_progress_size = 2131099649;
			
			// aapt resource value: 0x7f060007
			public static int place_autocomplete_separator_start = 2131099655;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int bubble_mask = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int bubble_shadow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int common_full_open_on_phone = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int common_google_signin_btn_icon_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int common_google_signin_btn_icon_dark_disabled = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int common_google_signin_btn_icon_dark_focused = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int common_google_signin_btn_icon_dark_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int common_google_signin_btn_icon_dark_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int common_google_signin_btn_icon_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int common_google_signin_btn_icon_light_disabled = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int common_google_signin_btn_icon_light_focused = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int common_google_signin_btn_icon_light_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int common_google_signin_btn_icon_light_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int common_google_signin_btn_text_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int common_google_signin_btn_text_dark_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int common_google_signin_btn_text_dark_focused = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int common_google_signin_btn_text_dark_normal = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int common_google_signin_btn_text_dark_pressed = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int common_google_signin_btn_text_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int common_google_signin_btn_text_light_disabled = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int common_google_signin_btn_text_light_focused = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int common_google_signin_btn_text_light_normal = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int common_google_signin_btn_text_light_pressed = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int common_ic_googleplayservices = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int common_plus_signin_btn_icon_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int common_plus_signin_btn_icon_dark_disabled = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int common_plus_signin_btn_icon_dark_focused = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public static int common_plus_signin_btn_icon_dark_normal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public static int common_plus_signin_btn_icon_dark_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public static int common_plus_signin_btn_icon_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public static int common_plus_signin_btn_icon_light_disabled = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public static int common_plus_signin_btn_icon_light_focused = 2130837535;
			
			// aapt resource value: 0x7f020020
			public static int common_plus_signin_btn_icon_light_normal = 2130837536;
			
			// aapt resource value: 0x7f020021
			public static int common_plus_signin_btn_icon_light_pressed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public static int common_plus_signin_btn_text_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public static int common_plus_signin_btn_text_dark_disabled = 2130837539;
			
			// aapt resource value: 0x7f020024
			public static int common_plus_signin_btn_text_dark_focused = 2130837540;
			
			// aapt resource value: 0x7f020025
			public static int common_plus_signin_btn_text_dark_normal = 2130837541;
			
			// aapt resource value: 0x7f020026
			public static int common_plus_signin_btn_text_dark_pressed = 2130837542;
			
			// aapt resource value: 0x7f020027
			public static int common_plus_signin_btn_text_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public static int common_plus_signin_btn_text_light_disabled = 2130837544;
			
			// aapt resource value: 0x7f020029
			public static int common_plus_signin_btn_text_light_focused = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public static int common_plus_signin_btn_text_light_normal = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public static int common_plus_signin_btn_text_light_pressed = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public static int places_ic_clear = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public static int places_ic_search = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public static int powered_by_google_dark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public static int powered_by_google_light = 2130837551;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000d
			public static int adjust_height = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public static int adjust_width = 2131230734;
			
			// aapt resource value: 0x7f08000a
			public static int auto = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public static int dark = 2131230731;
			
			// aapt resource value: 0x7f080002
			public static int hybrid = 2131230722;
			
			// aapt resource value: 0x7f080007
			public static int icon_only = 2131230727;
			
			// aapt resource value: 0x7f080000
			public static int item_touch_helper_previous_elevation = 2131230720;
			
			// aapt resource value: 0x7f08000c
			public static int light = 2131230732;
			
			// aapt resource value: 0x7f080003
			public static int none = 2131230723;
			
			// aapt resource value: 0x7f080004
			public static int normal = 2131230724;
			
			// aapt resource value: 0x7f080012
			public static int place_autocomplete_clear_button = 2131230738;
			
			// aapt resource value: 0x7f080014
			public static int place_autocomplete_powered_by_google = 2131230740;
			
			// aapt resource value: 0x7f080016
			public static int place_autocomplete_prediction_primary_text = 2131230742;
			
			// aapt resource value: 0x7f080017
			public static int place_autocomplete_prediction_secondary_text = 2131230743;
			
			// aapt resource value: 0x7f080015
			public static int place_autocomplete_progress = 2131230741;
			
			// aapt resource value: 0x7f080010
			public static int place_autocomplete_search_button = 2131230736;
			
			// aapt resource value: 0x7f080011
			public static int place_autocomplete_search_input = 2131230737;
			
			// aapt resource value: 0x7f080013
			public static int place_autocomplete_separator = 2131230739;
			
			// aapt resource value: 0x7f080005
			public static int satellite = 2131230725;
			
			// aapt resource value: 0x7f080008
			public static int standard = 2131230728;
			
			// aapt resource value: 0x7f080006
			public static int terrain = 2131230726;
			
			// aapt resource value: 0x7f080001
			public static int text = 2131230721;
			
			// aapt resource value: 0x7f080018
			public static int webview = 2131230744;
			
			// aapt resource value: 0x7f080009
			public static int wide = 2131230729;
			
			// aapt resource value: 0x7f08000f
			public static int window = 2131230735;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public static int google_play_services_version = 2131296256;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int info_window = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int place_autocomplete_fragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int place_autocomplete_item_powered_by_google = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int place_autocomplete_item_prediction = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int place_autocomplete_progress = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int text_bubble = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int webview = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public static int ballon_gx_prefix = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int basic_folder = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int basic_placemark = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int cdata = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int default_balloon = 2130968580;
			
			// aapt resource value: 0x7f040005
			public static int document_nest = 2130968581;
			
			// aapt resource value: 0x7f040006
			public static int draw_order_ground_overlay = 2130968582;
			
			// aapt resource value: 0x7f040007
			public static int extended_data = 2130968583;
			
			// aapt resource value: 0x7f040008
			public static int ground_overlay = 2130968584;
			
			// aapt resource value: 0x7f040009
			public static int ground_overlay_color = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public static int inline_style = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public static int multigeometry_placemarks = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public static int multiple_placemarks = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public static int nested_folders = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public static int nested_multigeometry = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public static int unknwown_folder = 2130968591;
			
			// aapt resource value: 0x7f040010
			public static int unsupported = 2130968592;
			
			// aapt resource value: 0x7f040011
			public static int visibility_ground_overlay = 2130968593;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f07001f
			public static int auth_google_play_services_client_facebook_display_name = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public static int auth_google_play_services_client_google_display_name = 2131165214;
			
			// aapt resource value: 0x7f070017
			public static int common_google_play_services_api_unavailable_text = 2131165207;
			
			// aapt resource value: 0x7f070009
			public static int common_google_play_services_enable_button = 2131165193;
			
			// aapt resource value: 0x7f070008
			public static int common_google_play_services_enable_text = 2131165192;
			
			// aapt resource value: 0x7f070007
			public static int common_google_play_services_enable_title = 2131165191;
			
			// aapt resource value: 0x7f070006
			public static int common_google_play_services_install_button = 2131165190;
			
			// aapt resource value: 0x7f070004
			public static int common_google_play_services_install_text_phone = 2131165188;
			
			// aapt resource value: 0x7f070005
			public static int common_google_play_services_install_text_tablet = 2131165189;
			
			// aapt resource value: 0x7f070003
			public static int common_google_play_services_install_title = 2131165187;
			
			// aapt resource value: 0x7f070012
			public static int common_google_play_services_invalid_account_text = 2131165202;
			
			// aapt resource value: 0x7f070011
			public static int common_google_play_services_invalid_account_title = 2131165201;
			
			// aapt resource value: 0x7f070010
			public static int common_google_play_services_network_error_text = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public static int common_google_play_services_network_error_title = 2131165199;
			
			// aapt resource value: 0x7f070002
			public static int common_google_play_services_notification_ticker = 2131165186;
			
			// aapt resource value: 0x7f07001b
			public static int common_google_play_services_restricted_profile_text = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public static int common_google_play_services_restricted_profile_title = 2131165210;
			
			// aapt resource value: 0x7f070019
			public static int common_google_play_services_sign_in_failed_text = 2131165209;
			
			// aapt resource value: 0x7f070018
			public static int common_google_play_services_sign_in_failed_title = 2131165208;
			
			// aapt resource value: 0x7f070020
			public static int common_google_play_services_unknown_issue = 2131165216;
			
			// aapt resource value: 0x7f070014
			public static int common_google_play_services_unsupported_text = 2131165204;
			
			// aapt resource value: 0x7f070013
			public static int common_google_play_services_unsupported_title = 2131165203;
			
			// aapt resource value: 0x7f070015
			public static int common_google_play_services_update_button = 2131165205;
			
			// aapt resource value: 0x7f07000b
			public static int common_google_play_services_update_text = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public static int common_google_play_services_update_title = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public static int common_google_play_services_updating_text = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public static int common_google_play_services_updating_title = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public static int common_google_play_services_wear_update_text = 2131165196;
			
			// aapt resource value: 0x7f070016
			public static int common_open_on_phone = 2131165206;
			
			// aapt resource value: 0x7f07001c
			public static int common_signin_button_text = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public static int common_signin_button_text_long = 2131165213;
			
			// aapt resource value: 0x7f070001
			public static int place_autocomplete_clear_button = 2131165185;
			
			// aapt resource value: 0x7f070000
			public static int place_autocomplete_search_hint = 2131165184;
			
			// aapt resource value: 0x7f070021
			public static int show_detail_capability_name = 2131165217;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public static int Bubble_TextAppearance_Dark = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public static int Bubble_TextAppearance_Light = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public static int ClusterIcon_TextAppearance = 2131361794;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771992,
					2130771993,
					2130771994};
			
			// aapt resource value: 2
			public static int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public static int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public static int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public static int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public static int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public static int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public static int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public static int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public static int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public static int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public static int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public static int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public static int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public static int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public static int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public static int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public static int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public static int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public static int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public static int MapAttrs_zOrderOnTop = 14;
			
			public static int[] RecyclerView = new int[]
			{
					16842948,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 0
			public static int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public static int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public static int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public static int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public static int RecyclerView_stackFromEnd = 4;
			
			public static int[] SignInButton = new int[]
			{
					2130771989,
					2130771990,
					2130771991};
			
			// aapt resource value: 0
			public static int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public static int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public static int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
